First HTML CSS
ichsansandy/hello-microverse pull request #1
Opened 2023-04-24 13:14 UTC by ichsansandy

This is the first project to get used to the tools we use in microverse 

in this project I created :
- index.html with h1 tag with the class heading
- style.css with the class heading to styling 
- test.md and exclude it by using .gitignore

2023-04-24 17:03 UTC, Shisui6 requested changes
Hi @ichsansandy, 

# Requires Changes 🍀
You have done a great job so far!👏👏
Your project is almost complete. We just need to fix a few issues🪲

## Highlights
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Linters are passing ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

- Please always remember to start your commit messages with a capital letter. This is considered best practice for making commits. E.g `Add style.css with heading class`

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-24 17:03 UTC, Shisui6 commented on .gitignore
> +package.json
Nice job adding node modules and test.md to gitignore👍. However, there is no need also to ignore `package.json` and `package-lock.json` as these files contain your project dependencies and will be needed by anyone who wants to clone your project to their local machine.

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +</div> -->
Please remove all comments that don't describe the code itself. This helps keep your code clean🙏

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +# 📖 [your_project_name] <a name="about-project"></a>
Please replace `[your_project_name]` with a title for your project🙏

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +> Its a first project to get to know the tools like linters and github flow
Please remove the `>` at the beginning of this line. The `>` makes the line appear as a comment and not actual text, which is not the intention.

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +    <li><a href="https://reactjs.org/">React.js</a></li>
Please replace the tech stack to include the technologies used for this project. You can add HTML and CSS
```suggestion
    <li><a href="#">HTML</a></li>
    <li><a href="#">CSS</a></li>
```

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +> It have linter for html
Please remove the `>` at the beginning of this line for the reasons explained above

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Since this project will not be deployed, you can remove this entire section. However, please note that for projects where you are required to deploy your project, this section **must** be present

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Please update this section to include instructions for how to get your project up and running on your users' local machines. This section is very important because, without it, nobody will know how to use your project😖

- You can use the provided example commands. However, please personalize them to match your project
- You can remove the run tests and deployment sections since they are not relevant to this project. However, please note that for projects where you are required to test and deploy your project, these sections must be present

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +> Mention all of the collaborators of this project.
Please remove this line as it is simply a comment👍

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
Please update this section to include your contact information. This section is very important to line users and potential employees to your other social profiles

- Please replace `Author1` with your name
- Please update the URLs for each social application with your own social URLs 
- Please remove the entire author2 as you are the sole author of this project

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +> Describe 1 - 3 features you will add to the project.
Please remove this line as it is simply a comment👍

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +- [ ] **[new_feature_3]**
Please replace `[new_feature_x]` with 1-3 features you plan to add to this project in the future. This section is also very important as it informs potential future collaborators on what they can collaborate with you on💪

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +> Write a message to encourage readers to support your project
Please remove this line as it is simply a comment👍

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +If you like this project...
Please add a message encouraging people to support your project

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +> Give credit to everyone who inspired your codebase.
Please remove this line as it is simply a comment👍

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +I would like to thank...
Please add a message thanking anyone who inspired this project🙏

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Please delete this section if you don't want to add an FAQ to your readme. It is the only optional section in the readme file

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
Please delete this line, as it is simply a note showing you how to fill this section and should not be present in the final readme

2023-04-24 17:03 UTC, Shisui6 commented on README.md
> +- [📝 License](#license)
Please remove all the extra text added to the table of content. This section should simply link to other sections in your readme. Please remove the extra text at about, tech stack, and author

2023-04-25 01:35 UTC, ichsansandy commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
still confused about this one but I put it like this I hope this right

## 💻 Getting Started <a name="getting-started"></a>

To get a local copy up and running, follow these steps.

### Setup

Clone this repository to your desired folder:

```sh
  cd my-folder
  git clone https://github.com/ichsansandy/hello-microverse.git
```
This project just contains an index.html and style.css with linters to check for any error

2023-04-25 05:14 UTC, Shisui6 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
@ichsansandy this works, well done✨. You applied all my suggestions, and your readme is looking really good🙌. 

Although if you really want to stand out, try editing this section to look like this:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/37116322/234180287-10bb5264-edae-4168-9ca3-f3003944feca.png">

2023-04-25 07:06 UTC, ichsansandy commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
@Shisui6 Great, thanks for reviewing mine, I already submit the review, hope to meet you in the next project

2023-04-25 07:13 UTC, wayungi approved these changes
Hi @ichsansandy , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All linter checks passing ✔️ 
- [ ] Good use  of the .gitignore file ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 07:40 UTC, merged